#!/bin/bash

set -e

echo "==> Removendo pacotes de fontes da Microsoft (incluindo Verdana)..."
sudo apt remove --purge -y ttf-mscorefonts-installer msttcorefonts

echo "==> Removendo arquivos da fonte Verdana dos diretórios comuns..."
find /usr/share/fonts -iname "*verdana*" -exec sudo rm -v {} \;
find /usr/local/share/fonts -iname "*verdana*" -exec sudo rm -v {} \;

echo "==> Fazendo backup do /etc/fonts/fonts.conf..."
sudo cp /etc/fonts/fonts.conf /etc/fonts/fontsbackup.conf

echo "==> Substituindo conteúdo de /etc/fonts/fonts.conf com nova configuração..."
sudo tee /etc/fonts/fonts.conf > /dev/null << 'EOF'
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- /etc/fonts/fonts.conf file to configure system font access -->
<fontconfig>
	<description>Default configuration file</description>

<!--
	DO NOT EDIT THIS FILE.
	IT WILL BE REPLACED WHEN FONTCONFIG IS UPDATED.
	LOCAL CHANGES BELONG IN 'local.conf'.
-->

	<dir>/usr/share/fonts</dir>
	<dir>/usr/local/share/fonts</dir>
	<dir prefix="xdg">fonts</dir>
	<dir>~/.fonts</dir>

	<match target="pattern">
		<test qual="any" name="family">
			<string>mono</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>monospace</string>
		</edit>
	</match>

	<match target="pattern">
		<test qual="any" name="family">
			<string>sans serif</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

	<match target="pattern">
		<test qual="any" name="family">
			<string>sans</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>sans-serif</string>
		</edit>
	</match>

	<match target="pattern">
		<test qual="any" name="family">
			<string>system ui</string>
		</test>
		<edit name="family" mode="assign" binding="same">
			<string>system-ui</string>
		</edit>
	</match>

	<selectfont>
		<rejectfont>
			<glob>*.dpkg-tmp</glob>
		</rejectfont>
	</selectfont>
	<selectfont>
		<rejectfont>
			<glob>*.dpkg-new</glob>
		</rejectfont>
	</selectfont>

	<include ignore_missing="yes">conf.d</include>

	<cachedir>/var/cache/fontconfig</cachedir>
	<cachedir prefix="xdg">fontconfig</cachedir>
	<cachedir>~/.fontconfig</cachedir>

	<config>
		<rescan>
			<int>30</int>
		</rescan>
	</config>

    <match target="pattern">
        <test qual="any" name="family">
            <string>Verdana</string>
        </test>
        <edit name="family" mode="assign" binding="strong">
            <string>Terminus</string>
        </edit>
    </match>

    <match target="pattern">
        <test name="family" qual="any">
            <string>Verdana</string>
        </test>
        <test name="weight" compare="more_eq">
            <int>200</int>
        </test>
        <edit name="family" mode="assign">
            <string>Terminus</string>
        </edit>
    </match>
</fontconfig>
EOF

echo "==> Instalando fonte Terminus..."
sudo apt update
sudo apt install -y xfonts-terminus

echo "==> Criando diretório de configuração local de fontes se necessário..."
mkdir -p ~/.config/fontconfig

LOCAL_FONTS_CONF=~/.config/fontconfig/fonts.conf

echo "==> Adicionando configuração local para substituir Verdana por Terminus..."
cat > "$LOCAL_FONTS_CONF" << EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="pattern">
        <test qual="any" name="family">
            <string>Verdana</string>
        </test>
        <edit name="family" mode="assign" binding="strong">
            <string>Terminus</string>
        </edit>
    </match>

    <match target="pattern">
        <test name="family" qual="any">
            <string>Verdana</string>
        </test>
        <test name="weight" compare="more_eq">
            <int>200</int>
        </test>
        <edit name="family" mode="assign">
            <string>Terminus</string>
        </edit>
    </match>
</fontconfig>
EOF

echo "==> Atualizando cache de fontes..."
fc-cache -f -v

echo "==> Remoção da fonte Verdana e substituição por Terminus concluída com sucesso."
